### ISSUE TITLE
Style sign in pages

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/dda#20]
### Acceptance Criteria:
* Style sign in pages according to designs
* Use buttons created in #18 
* Omit the logo for now
* Sign in page should have a "If you are DDA staff or an employer please login here" button

**Comment by shanben7** [comment]
<img width="250" alt="Screen Shot 2019-03-27 at 3 50 32 PM" src="https://user-images.githubusercontent.com/25892055/55117458-2959f580-50a8-11e9-9699-e4999115ddc9.png"><img width="250" alt="Screen Shot 2019-03-27 at 3 50 39 PM" src="https://user-images.githubusercontent.com/25892055/55117461-2c54e600-50a8-11e9-8e98-fe0bcd5af66e.png">
