### ISSUE TITLE
Create ApiGateway endpoints using swagger file

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/dda#8]
### Acceptance Criteria:
* Create an API on ApiGateway using swagger file created in #13 
* Connect each endpoint to their respective Lambda functions created in #9 
* Do not deploy API yet
* Update wiki with ApiGateway architecture

**Comment by vinielk** [comment]
@kouitayakul You don't have to connect the endpoints to the lambda functions as part of this ticket. We can create another ticket for that once the lambda functions are done.
